-d /home/tallguydesi/Documents/GitHub/Dino-Game-128x64-OLED-using-FPGA/impl/gwsynthesis/Functional_60FPS.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/tallguydesi/Documents/GitHub/Dino-Game-128x64-OLED-using-FPGA/src/Functional_60FPS.cst
-cfg /home/tallguydesi/Documents/GitHub/Dino-Game-128x64-OLED-using-FPGA/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
